### ISSUE TITLE
Read CodecPrivate from Track

### ISSUE THREAD

**Issue by melchor629** [tuffy/matroska#4]
Hi!

I would like to request a new feature which is the ability to read the `CodecPrivate` section from the `TrackEntry`.

This is useful for example when reading SSA/ASS subtitles, which the initial content of them are [stored in this region](https://matroska.org/technical/subtitles.html). I'm using your crate to read the MKVs metadata, just to after demux it to extract the subtitles, using another crate. Your's provide more complete information about the metadata, except for the `CodecPrivate` which I would appreciate.

Thanks in advance!!

**Comment by astraw** [comment]
It looks like this was implemented in b0807d741fd4176030bb86e52b3ab21d69ed78b2, and released in 0.16.0. I think this issue can be closed.

**Comment by melchor629** [comment]
Oh cool. Closing the issue, thanks!!
